---
name: Data-asXML
version: 0.05
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: convert data structures to/from XML
license: perl
resources:
  bugtracker: http://github.com/jozef/Data-asXML/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/Data-asXML.git
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Encode: 0
  MIME::Base64: 0
  Test::Deep::NoTest: 0
  XML::LibXML: 0
configure_requires:
  Module::Build: 0.35
provides:
  Data::asXML:
    file: lib/Data/asXML.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - data
  - xml
  - structure
